name: Run shell script
on: push
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run script file
        run: |
          bash ./code_etr --input-path example/source_code --name aug18testing scan
        shell: bash
