name: Run shell script
on: push
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run script file
        run: |
          python -m venv venvcodeetr
          source venvcodeetr/bin/activate
          pip3 install pyyaml
          pip3 install jproperties
          pip3 install sqlparse
          bash ./code_etr --input-path example/source_code --name aug18testing scan
        shell: bash
      - uses: actions/upload-artifact@v3
        with:
          name: output-log-file
          path: set_files/**
          if-no-files-found: error
    
